apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: or3534/demo_app:latest  # Specify your Docker image
        ports:
        - containerPort: 5000  # Port your Flask app is listening on
